GET https://arcane-chamber-78631.herokuapp.com/api/v1/flower

###
POST https://arcane-chamber-78631.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "sepalLength": 12,
  "color": 1,
  "price": 100,
  "flowerType": 0
}